
GET http://localhost:3001/api/notes

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "VS Code client test AGAIN",
  "important": true
}

###
DELETE http://localhost:3001/api/notes/68863b80df30fb606670bbf6