
GET http://localhost:3001/api/blogs

###
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3QxIiwiaWQiOiI2ODlkZjVlN2FmOWIwZDQyZWQ5NmJlYzIiLCJpYXQiOjE3NTUyNzEwMjYsImV4cCI6MTc1NTI4MTgyNn0.bp-fs8jQaBbfuXt-ZG3mdUx3nsrzO8vD74bovs235mM

{
  "title": "Test Title3",
  "author": "Test Author3",
  "url": "testurl.com3",
  "likes": 5
}

###
DELETE http://localhost:3001/api/blogs/689f482fd86532becc037b51
Content-Type: application/json


###
PUT http://localhost:3001/api/blogs/688e3192194df533c1949f85
Content-Type: application/json

{
  "title": "Test Title",
  "author": "Test Author",
  "url": "testurl.com",
  "likes": false
}

###
GET http://localhost:3001/api/users

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "Test1",
  "name": "Test1",
  "password": "Test1"
}

###
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "Test1",
  "password": "Test1"
}