
GET http://localhost:3001/api/blogs

###
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3QxIiwiaWQiOiI2ODlkZjVlN2FmOWIwZDQyZWQ5NmJlYzIiLCJpYXQiOjE3NTUzNTUyMDgsImV4cCI6MTc1NTM2NjAwOH0.dljdSvmGkf7tsKXCrVJlzWRrYzE51EwaZOWSy0Ql0uA

{
  "title": "Test Title2",
  "author": "Test Author2",
  "url": "testurl.com2",
  "likes": 5
}

###
DELETE http://localhost:3001/api/blogs/689f487c89838df19c7a63a7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3QxIiwiaWQiOiI2ODlkZjVlN2FmOWIwZDQyZWQ5NmJlYzIiLCJpYXQiOjE3NTUzNTY3NTMsImV4cCI6MTc1NTM2NzU1M30.F6f4vAYMnhbYzr6oPfe8ayTarjpqC6iCC8AXVVB1z7Q


###
PUT http://localhost:3001/api/blogs/688e3192194df533c1949f85
Content-Type: application/json

{
  "title": "Test Title",
  "author": "Test Author",
  "url": "testurl.com",
  "likes": false
}

###
GET http://localhost:3001/api/users

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "Test2",
  "name": "Test2",
  "password": "Test2"
}

###
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "Test1",
  "password": "Test1"
}