
GET http://localhost:3001/api/blogs

###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "Test Title",
  "author": "Test Author",
  "url": "testurl.com",
  "likes": 5
}